Write blog post: Improving our Document Outline
ZeitOnline/frontend-developer-handbook pull request #17
Opened 2020-11-27 10:33 UTC by thomaspuppe

Der Post ist schon etwas älter, und war in einem Branch verschimmelt. Jetzt nochmal neu.

2020-11-27 11:33 UTC, codecandies requested changes
Oh klasse :) Hab's mal durch meinen Englisch-Checker laufen lassen und ein paar kleinere Änderungen vorgeschlagen danach… :=

2020-11-27 11:33 UTC, codecandies commented on blog/document-outline.md
> +## what is the document outline?
Die Zwischenüberschriften würde ich als Quasisatzanfang immer großgeschrieben anfangen…

2020-11-27 11:33 UTC, codecandies commented on blog/document-outline.md
> +That whole topic is a [big dilemma](https://css-tricks.com/document-outline-dilemma/), but nevertheless we can try to improve our sites in order to explain the sites structure to people (or machines)
`in order to` ==> `to` (mein Grammatikchecker sagt: "Consider a shorter alternative to acoid wordiness" ;) )

2020-11-27 11:33 UTC, codecandies commented on blog/document-outline.md
> +There are ways to make the document outline visible. The easiest one is a chrome browser extension "[HTML Outliner](https://chrome.google.com/webstore/detail/html5-outliner/afoibpobokebhgfnknfndkgemg
`Chrome` als Namen großschreiben

2020-11-27 11:33 UTC, codecandies commented on blog/document-outline.md
> +The document outline represents the logical or semantical structure of an HTML document. This is a little difficult, because there are two concepts: hierarchy of headlines `h1` to `h6` and the nested
Kein Komma vor `because`… if the because clause is essential to the meaning (englische Punktuation ist echt das allerletzte)

2020-11-27 11:33 UTC, codecandies commented on blog/document-outline.md
> +By assigning headline status to text nodes which do not look like headlines (in our case descriptions of products in our shop, these nodes get respected as the elements title in the document outline.
`)` fehlt

2020-11-27 11:33 UTC, codecandies commented on blog/document-outline.md
> +The HTML Checker provides [two kinds of outline](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.zeit.de%2Findex), which perfectly illustrates the dilemma mentioned above:
`perfectly illustrates` ==> `illustrates perfectly` (adverbial construction)

2020-11-27 16:26 UTC, thomaspuppe commented
Hab ich gemacht. Welches Tool benutzt du denn als English Checker?

2020-11-30 13:53 UTC, merged

2020-11-30 13:54 UTC, codecandies commented
@thomaspuppe die ust in Ulysses eingebaut, meinem Schreibtool für alles